/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package powertoys;

import javax.swing.JFrame;
import java.awt.*;

public class App {
    public static void main(String[] args) {
        //TODO Give own class
        //TODO Add menubar with license and link to pag
        JFrame mainWindow = new JFrame();
        Button fileSorterButton = new Button("File Sorter");
        Button randomFileChooserButton = new Button("Random File Chooser");
        Button fileUnsorterButton = new Button("File Unsorter");

        mainWindow.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        mainWindow.setSize(500, 300);
        mainWindow.setLocation(100, 100);
        mainWindow.setLayout(new FlowLayout());
        mainWindow.setTitle("PowerToys");

        mainWindow.add(fileSorterButton);
        mainWindow.add(randomFileChooserButton);
        mainWindow.add(fileUnsorterButton);

        mainWindow.setVisible(true);
    }
}
