/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package powertoys;

import com.sun.tools.javac.Main;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class App {
    public static void main(String[] args) {
        //TODO Add menubar with license and link to pag
        JFrame window = new JFrame();
        window.setTitle("PowerToys");
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        window.setSize(500, 300);
        window.setLocation(100, 100);

        MainWindow MainWindow = new MainWindow(window);
        window.add(MainWindow);

        window.setVisible(true);
    }

}
